modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mead"
version = "${version}"
displayName = "Mead"
authors = "ZedDevStuff"
description = '''
A XML based UI framework for Minecraft
'''
#logoFile = ""

[[dependencies.mead]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mead]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "mead.mixins.json"
